# Generated by Django 4.1.4 on 2023-01-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_shop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
    ]
